### ISSUE TITLE
Parameter 'LeScale' is deprecated now

### ISSUE THREAD

**Issue by pbrt4bounty** [shadeops/pbrt-v4-volumes#2]
I found some annoying error testing your scenes because  the parameter 'LeScale' is now deprecated and 'Lescale' is used instead.
Cheers..

**Comment by shadeops** [comment]
Ya LeScale and temperatureoffset changed recently in 
[6743986](https://github.com/mmp/pbrt-v4/commit/6743986a374d563b19314b1a88f74a499d8ad38f) and [5e0884f7](https://github.com/mmp/pbrt-v4/commit/5e0884f7b7094b273a720a22c5f261ce2e894299)

I updated the exporter right after but completely forgot to update volume examples, thanks for the reminder!

Fixed in [b440080](https://github.com/shadeops/pbrt-v4-volumes/commit/b440080926835aa6167c6900e8c3f7486fcd29cc)
